version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger_pipeline:
    type: boolean
    default: true
  image_name:
    type: string
    default: speech_recognition_model_api
  package_version:
    type: string
    default: "2.0.0"
  dependency_image_name:
    type: string
    default: speech-recognition-open-api-dependency
  dependency_version:
    type: string
    default: "1.0"
  platform:
    default: "gke"
    type: enum
    enum: ["gke", "eks", "cdac"]
  build_dependency:
    type: boolean
    default: false

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
      resource_class: 2xlarge
    working_directory: ~/speech-recognition-model-api/
    steps:
      - checkout:
          path: ~/speech-recognition-model-api
      - run:
          name: Setup Google credentials
          command: |
            echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
            pip install google_compute_engine
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project ${GCP_PROJECT}
      - run:
          name: Build dependencies image
          command: |
            echo "Build ..."
            if << pipeline.parameters.build_dependency >> ; then
              docker build --rm=false -t gcr.io/${GCP_PROJECT}/<< pipeline.parameters.dependency_image_name >>:<< pipeline.parameters.dependency_version >> dependencies/
              gcloud docker -- push gcr.io/${GCP_PROJECT}/<< pipeline.parameters.dependency_image_name >>:<< pipeline.parameters.dependency_version >>
            fi
#      - when:
#          condition:
#            equal: [ true, << pipeline.paramaters.build_dependency >> ]
#          steps:
#            - run: |
#                docker build --rm=false -t gcr.io/${GCP_PROJECT}/<< pipeline.parameters.dependency_image_name >>:<< pipeline.parameters.dependency_version >> dependencies/
#                gcloud docker -- push gcr.io/${GCP_PROJECT}/<< pipeline.parameters.dependency_image_name >>:<< pipeline.parameters.dependency_version >>
      - run:
          name: Build docker image
          command: |
            echo "Build ..."
            docker build --rm=false -t gcr.io/${GCP_PROJECT}/<< pipeline.parameters.image_name >>:<< pipeline.parameters.package_version >> .
      - run:
          name: deploy image to registry
          command: |
            echo "Deploy ..."
            gcloud docker -- push gcr.io/${GCP_PROJECT}/<< pipeline.parameters.image_name >>:<< pipeline.parameters.package_version >>
      - run:
          name: Remove account details
          command: |
            rm ${HOME}/gcp-key.json ; ls

  deploy:
    machine:
      image: ubuntu-2004:202101-01
      resource_class: 2xlarge
    working_directory: ~/speech-recognition-model-api/
    steps:
      - attach_workspace:
          at: ~/speech-recognition-model-api
      - checkout:
          path: ~/speech-recognition-model-api
      - run:
          name: Setup Google credentials
          command: |
            echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
            pip install google_compute_engine
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project ${GCP_PROJECT}
      - run:
          name: Install and confgure kubectl
          command: sudo curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && sudo chmod +x /usr/local/bin/kubectl  
      - run:
          name: Install and configuire helm
          command: sh scripts/install_helm.sh    
      - run:
          name: Configure aws
          command: sh scripts/<< pipeline.parameters.platform >>-setup.sh 
      - run:
          name: Release model using helm chart 
          command: python deploy.py
      - run:
          name: Remove account details
          command: |
            rm ${HOME}/gcp-key.json ; ls

workflows:
  version: 2
  main_workflow:
    when: << pipeline.parameters.trigger_pipeline >>
    jobs:
     - build:
         name: build
         filters:
           branches:
             only: test-helm
     - deploy:
         name: deploy
         filters:
           branches:
             only: test-helm
         requires:
           - build
