apiVersion: v1
kind: Service
metadata:
  name: {{ include "asr-model-v2.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "asr-model-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "asr-model-v2.selectorLabels" . | nindent 4 }}
